### ISSUE TITLE
Feature Request: missing fields in mzML

### ISSUE THREAD

**Issue by dtabb73** [gtluu/timsconvert#47] opened 2023-09-21 10:23 UTC
Hello, I'd like to request that TIMSConvert export the following fields for each experiment to the corresponding mzML:

- Instrument Model (for example MS:1003383 or MS:1003005)
- Serial Number (MS:1000529)
- StartTimeStamp (in run element)
- Activation type (for example MS:1000133, MS:1000422, MS:1000250, or MS:1000598, alongside the currently reported MS:1000045)

I read these fields in my quality control software, but at present they are not included in TIMSConvert's output.
Thanks!

**Comment by gtluu** [comment] 2023-09-21 16:27
Hi Dave, I will look into this. Originally this information was intentionally not included due to incompatibility with some commonly used downstream software, but it's definitely time to revisit this. Will post updates as they come.

**Comment by gtluu** [comment] 2023-09-29 19:12
@dtabb73 the request metadata should be added to the written mzML files as of 12f36110fa8ebdf2ce8f36a8a275532876fce453. I'll close this out now but feel free to reach out if any unexpected behavior is encountered.

**Closed by gtluu** 2023-09-29 19:12 UTC
